# Generated by Django 3.2.6 on 2021-08-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_auto_20210816_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=64, null=True, unique=True)),
                ('checkout_request_id', models.CharField(max_length=64, null=True, unique=True)),
                ('mpesa_code', models.CharField(max_length=64, null=True, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('reason_failed', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('transaction_cost', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('requested', 'Payment Requested'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success')], default='requested', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
