# Generated by Django 3.2.6 on 2021-11-15 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
        ('m_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstate',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='buyers.buyer'),
        ),
    ]
