# Generated by Django 3.2.6 on 2021-09-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstate',
            name='context',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
