# Generated by Django 3.2.6 on 2022-05-01 19:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0003_rename_phone_number_buyer_phone'),
        ('products', '0007_product_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Successful Payment'), ('failed', 'Payment Failed'), ('cancelled', 'Payment Cancelled'), ('pending', 'Payment Pending')], default='pending', max_length=10)),
                ('payment_method', models.CharField(max_length=50, null=True)),
                ('payment_proof', models.FileField(null=True, upload_to='payment_proofs')),
                ('transaction_id', models.CharField(max_length=50, null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='buyers.buyer')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Quantity cannot be less than one')])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_items', to='products.product')),
            ],
            options={
                'unique_together': {('invoice', 'product')},
            },
        ),
    ]
