# Generated by Django 3.0.7 on 2021-08-10 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Random', max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='buyers.Buyer')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
