# Generated by Django 3.2.6 on 2021-11-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='business_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
