# Generated by Django 3.0.7 on 2020-06-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_auto_20200624_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ContactQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Random', max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='buyers.Buyer')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
