# Generated by Django 3.2.6 on 2021-11-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_auto_20211116_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
