# Generated by Django 3.0.7 on 2020-06-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
    ]
