# Generated by Django 3.2.6 on 2021-08-12 20:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('prep', 'Preparing'), ('ship', 'On Transit'), ('fin', 'Delivery Finished'), ('can', 'Delivery Cancelled')], default='prep', max_length=4)),
                ('payment_status', models.CharField(choices=[('success', 'Successful Payment'), ('failed', 'Payment Failed '), ('pending', 'Payment Pending ')], default='pending', max_length=10)),
                ('payment_method', models.CharField(choices=[('m-pesa', 'M-Pesa'), ('on-delivery', 'On Delivery')], default='on-delivery', max_length=15)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='buyers.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMpesaTransaction',
            fields=[
                ('transaction_id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('mpesa_transaction_id', models.CharField(editable=False, max_length=200, null=True, unique=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', editable=False, max_length=10)),
                ('order', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Quantity cannot be less than one')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='products.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
