# Generated by Django 3.0.7 on 2020-06-22 12:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('prep', 'Preparing'), ('ship', 'Preparing'), ('del', 'Delivered')], default='prep', max_length=4)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('prep', 'Preparing'), ('ship', 'Preparing'), ('del', 'Delivered')], default='on-delivery', max_length=15)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='buyers.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Quantity cannot be less than one')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
