# Generated by Django 3.0.7 on 2020-06-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('m-pesa', 'M-Pesa'), ('on-delivery', 'On Delivery')], default='on-delivery', max_length=15),
        ),
    ]
