# Generated by Django 3.2.6 on 2021-08-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('ussd', 'USSD'), ('sms', 'SMS'), ('whatsapp', 'Whatsapp')], default='whatsapp', max_length=15),
        ),
        migrations.DeleteModel(
            name='OrderMpesaTransaction',
        ),
    ]
