# Generated by Django 3.0.7 on 2020-06-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200624_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('success', 'Successful Payment'), ('failed', 'Payment Failed '), ('pending', 'Payment Pending ')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('prep', 'Preparing'), ('ship', 'On Transit'), ('del', 'Delivered'), ('can', 'Delivery Cancelled')], default='prep', max_length=4),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order'),
        ),
        migrations.CreateModel(
            name='OrderMpesaTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='orders.Order')),
            ],
        ),
    ]
