# Generated by Django 3.0.7 on 2020-06-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200625_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('prep', 'Preparing'), ('ship', 'On Transit'), ('fin', 'Delivery Finished'), ('can', 'Delivery Cancelled')], default='prep', max_length=4),
        ),
        migrations.CreateModel(
            name='OrderCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
