# Generated by Django 3.0.7 on 2020-06-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200625_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermpesatransaction',
            name='mpesa_transaction_id',
            field=models.CharField(editable=False, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ordermpesatransaction',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermpesatransaction',
            name='order',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='ordermpesatransaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
