# Generated by Django 3.0.7 on 2020-06-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_complementaryitem'),
        ('orders', '0005_auto_20200627_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='c_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='items.ComplementaryItem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='items.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'c_product'), ('order', 'product')},
        ),
    ]
