# Generated by Django 3.0.7 on 2021-08-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplementaryItem',
        ),
    ]
